export { NumericInput } from './components/NumericInput/NumericInput'
export { useWeb3Contract } from './hooks/useWeb3Contract'
export { removeEFromNumber } from './metamask/metamask'
export { networkSwitcher } from './metamask/metamask'
export { addTokenToMetamask } from './metamask/metamask'